services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: planet9
    ports:
      - 5432:5432
    volumes:
      - "pgdataV203:/var/lib/postgresql/data"
      - ./db-init:/docker-entrypoint-initdb.d
  dbgui:
    image: adminer
    restart: always
    ports:
      - 3000:8080
  planet9:
    image: neptunesoftware/planet9:v2.0.3
    environment:
      DB_URI_POSTGRES: postgress://myuser:mypassword@db:5432/planet9
      # Could be either 'sqlite', 'postgresql'
      DB_TYPE: postgresql
    ports:
      - 8080:8080
volumes:
  pgdataV203:
