services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: planet9
    ports:
      - 5432:5432
    volumes:
      - "pgdataV220:/var/lib/postgresql/data"
      - ./db-init:/docker-entrypoint-initdb.d
  dbgui:
    image: adminer
    restart: always
    ports:
      - 3000:8080
  planet9:
    image: neptunesoftware/planet9:v2.2.0
    environment:
      DB_URI_POSTGRES: postgress://myuser:mypassword@db:5432/planet9
      DB_TYPE: sqlite
      PORT: 8080
      ENABLE_SSL: "true"
      SSLCA: MYCA
      SSLCERT: MYCERT
      SSLKEY: MYKEY
    ports:
      - 8080:8080
volumes:
  pgdataV220:
